#!/usr/bin/env python3
"""
Hermes 每日站会报告生成器
用于快速生成每日进度报告，跟踪4周行动路线图执行情况
"""

import os
import sys
import json
import argparse
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict, Optional

TEMPLATE = """# Hermes 每日站会报告

**日期**: {date}
**团队**: Hermes Team
**汇报人**: [你的名字]

---

## 📊 昨日完成

{completed_items}

---

## 🎯 今日计划

{today_items}

---

## ⚠️  blockers（阻碍）

{blockers}

---

## 📈 指标更新

| 指标 | 昨日值 | 目标 | 状态 |
|------|--------|------|------|
| 调度延迟 P95 | {sched_latency}ms | < 500ms | {sched_status} |
| 故障恢复时间 | {recovery_time}s | < 5s | {recovery_status} |
| GPU利用率 | {gpu_util}% | > 85% | {gpu_status} |
| SLA达标率 | {sla}% | > 99.9% | {sla_status} |

---

## 📅 里程碑进度

| 阶段 | 目标 | 进度 | 状态 |
|------|------|------|------|
| 阶段一：试点完成 | 第1-2周 | {phase1_progress}% | {phase1_status} |
| 阶段二：有限推广 | 第3-4周 | {phase2_progress}% | {phase2_status} |
| 阶段三：全面接管 | 第5-8周 | {phase3_progress}% | {phase3_status} |

---

## 📝 备注

{notes}

---

*Generated by Hermes Daily Standup Generator*
"""

class DailyStandupGenerator:
    def __init__(self, output_dir: Path = Path(".")):
        self.output_dir = output_dir
        self.date = datetime.now().strftime("%Y-%m-%d")

    def load_previous_report(self) -> Optional[dict]:
        """加载昨天的报告"""
        yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
        report_path = self.output_dir / f"standup_{yesterday}.md"

        if report_path.exists():
            with open(report_path, 'r') as f:
                content = f.read()
            return self._parse_report(content)

        return None

    def _parse_report(self, content: str) -> dict:
        """解析报告内容"""
        # 简单解析，实际使用时可能需要更复杂的逻辑
        return {
            'date': self.date,
            'raw_content': content
        }

    def generate_report(
        self,
        completed: List[str],
        today: List[str],
        blockers: List[str],
        metrics: Dict[str, float],
        phase_progress: Dict[str, int],
        notes: str = ""
    ) -> str:
        """生成报告"""

        # 计算状态
        def get_status(actual: float, target: float, inverse: bool = False) -> str:
            if inverse:
                return "✅" if actual < target else "⚠️"
            return "✅" if actual >= target else "⚠️"

        # 生成里程碑状态
        def get_phase_status(progress: int) -> str:
            if progress >= 100:
                return "✅ 完成"
            elif progress >= 50:
                return "🔄 进行中"
            else:
                return "⏳ 准备中"

        # 格式化列表
        def format_list(items: List[str]) -> str:
            if not items:
                return "- 无"
            return "\n".join(f"- {item}" for item in items)

        report = TEMPLATE.format(
            date=self.date,
            completed_items=format_list(completed),
            today_items=format_list(today),
            blockers=format_list(blockers) if blockers else "- 无",
            sched_latency=metrics.get("sched_latency_ms", 0),
            sched_status=get_status(metrics.get("sched_latency_ms", 0), 500, inverse=True),
            recovery_time=metrics.get("recovery_time_s", 0),
            recovery_status=get_status(metrics.get("recovery_time_s", 0), 5, inverse=True),
            gpu_util=metrics.get("gpu_util", 0),
            gpu_status=get_status(metrics.get("gpu_util", 0), 85),
            sla=metrics.get("sla_compliance", 0),
            sla_status="✅" if metrics.get("sla_compliance", 0) >= 99.9 else "⚠️",
            phase1_progress=phase_progress.get("phase1", 0),
            phase1_status=get_phase_status(phase_progress.get("phase1", 0)),
            phase2_progress=phase_progress.get("phase2", 0),
            phase2_status=get_phase_status(phase_progress.get("phase2", 0)),
            phase3_progress=phase_progress.get("phase3", 0),
            phase3_status=get_phase_status(phase_progress.get("phase3", 0)),
            notes=notes if notes else "- 无"
        )

        return report

    def save_report(self, content: str) -> Path:
        """保存报告"""
        filename = f"standup_{self.date}.md"
        filepath = self.output_dir / filename

        with open(filepath, 'w') as f:
            f.write(content)

        print(f"✅ 报告已保存: {filepath}")
        return filepath

def main():
    parser = argparse.ArgumentParser(description="Hermes 每日站会报告生成器")
    parser.add_argument("--output-dir", default=".", help="输出目录")
    parser.add_argument("--completed", nargs="+", help="昨日完成项")
    parser.add_argument("--today", nargs="+", help="今日计划")
    parser.add_argument("--blockers", nargs="+", help="阻碍事项")
    parser.add_argument("--notes", default="", help="备注")
    parser.add_argument("--interactive", action="store_true", help="交互式输入")
    args = parser.parse_args()

    generator = DailyStandupGenerator(Path(args.output_dir))

    if args.interactive:
        print("📝 交互式输入模式")
        print("="*40)

        completed = []
        print("\n昨日完成 (输入空行结束):")
        while True:
            item = input("  > ")
            if not item.strip():
                break
            completed.append(item)

        today = []
        print("\n今日计划 (输入空行结束):")
        while True:
            item = input("  > ")
            if not item.strip():
                break
            today.append(item)

        blockers = []
        print("\n阻碍事项 (输入空行结束):")
        while True:
            item = input("  > ")
            if not item.strip():
                break
            blockers.append(item)

        notes = input("\n备注: ") or ""

        metrics = {
            "sched_latency_ms": 350,
            "recovery_time_s": 3.2,
            "gpu_util": 87,
            "sla_compliance": 99.95
        }

        phase_progress = {
            "phase1": 50,
            "phase2": 0,
            "phase3": 0
        }

    else:
        completed = args.completed or ["无"]
        today = args.today or ["无"]
        blockers = args.blockers or ["无"]
        notes = args.notes

        # 默认指标
        metrics = {
            "sched_latency_ms": 350,
            "recovery_time_s": 3.2,
            "gpu_util": 87,
            "sla_compliance": 99.95
        }

        phase_progress = {
            "phase1": 50,
            "phase2": 0,
            "phase3": 0
        }

    # 生成报告
    report = generator.generate_report(
        completed=completed,
        today=today,
        blockers=blockers,
        metrics=metrics,
        phase_progress=phase_progress,
        notes=notes
    )

    print("\n" + "="*60)
    print("📋 报告预览")
    print("="*60)
    print(report)

    # 保存
    filepath = generator.save_report(report)
    print(f"\n💡 下次查看: cat {filepath}")

if __name__ == "__main__":
    main()
