#!/usr/bin/env python3
"""
Hermes 
4
"""

import os
import sys
import json
import argparse
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict, Optional

TEMPLATE = """# Hermes 

****: {date}
****: Hermes Team
****: []

---

##  

{completed_items}

---

##  

{today_items}

---

##   blockers

{blockers}

---

##  

|  |  |  |  |
|------|--------|------|------|
|  P95 | {sched_latency}ms | < 500ms | {sched_status} |
|  | {recovery_time}s | < 5s | {recovery_status} |
| GPU | {gpu_util}% | > 85% | {gpu_status} |
| SLA | {sla}% | > 99.9% | {sla_status} |

---

##  

|  |  |  |  |
|------|------|------|------|
|  | 1-2 | {phase1_progress}% | {phase1_status} |
|  | 3-4 | {phase2_progress}% | {phase2_status} |
|  | 5-8 | {phase3_progress}% | {phase3_status} |

---

##  

{notes}

---

*Generated by Hermes Daily Standup Generator*
"""

class DailyStandupGenerator:
    def __init__(self, output_dir: Path = Path(".")):
        self.output_dir = output_dir
        self.date = datetime.now().strftime("%Y-%m-%d")

    def load_previous_report(self) -> Optional[dict]:
        """"""
        yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
        report_path = self.output_dir / f"standup_{yesterday}.md"

        if report_path.exists():
            with open(report_path, 'r') as f:
                content = f.read()
            return self._parse_report(content)

        return None

    def _parse_report(self, content: str) -> dict:
        """"""
        # 
        return {
            'date': self.date,
            'raw_content': content
        }

    def generate_report(
        self,
        completed: List[str],
        today: List[str],
        blockers: List[str],
        metrics: Dict[str, float],
        phase_progress: Dict[str, int],
        notes: str = ""
    ) -> str:
        """"""

        # 
        def get_status(actual: float, target: float, inverse: bool = False) -> str:
            if inverse:
                return "" if actual < target else ""
            return "" if actual >= target else ""

        # 
        def get_phase_status(progress: int) -> str:
            if progress >= 100:
                return " "
            elif progress >= 50:
                return " "
            else:
                return "⏳ "

        # 
        def format_list(items: List[str]) -> str:
            if not items:
                return "- "
            return "\n".join(f"- {item}" for item in items)

        report = TEMPLATE.format(
            date=self.date,
            completed_items=format_list(completed),
            today_items=format_list(today),
            blockers=format_list(blockers) if blockers else "- ",
            sched_latency=metrics.get("sched_latency_ms", 0),
            sched_status=get_status(metrics.get("sched_latency_ms", 0), 500, inverse=True),
            recovery_time=metrics.get("recovery_time_s", 0),
            recovery_status=get_status(metrics.get("recovery_time_s", 0), 5, inverse=True),
            gpu_util=metrics.get("gpu_util", 0),
            gpu_status=get_status(metrics.get("gpu_util", 0), 85),
            sla=metrics.get("sla_compliance", 0),
            sla_status="" if metrics.get("sla_compliance", 0) >= 99.9 else "",
            phase1_progress=phase_progress.get("phase1", 0),
            phase1_status=get_phase_status(phase_progress.get("phase1", 0)),
            phase2_progress=phase_progress.get("phase2", 0),
            phase2_status=get_phase_status(phase_progress.get("phase2", 0)),
            phase3_progress=phase_progress.get("phase3", 0),
            phase3_status=get_phase_status(phase_progress.get("phase3", 0)),
            notes=notes if notes else "- "
        )

        return report

    def save_report(self, content: str) -> Path:
        """"""
        filename = f"standup_{self.date}.md"
        filepath = self.output_dir / filename

        with open(filepath, 'w') as f:
            f.write(content)

        print(f" : {filepath}")
        return filepath

def main():
    parser = argparse.ArgumentParser(description="Hermes ")
    parser.add_argument("--output-dir", default=".", help="")
    parser.add_argument("--completed", nargs="+", help="")
    parser.add_argument("--today", nargs="+", help="")
    parser.add_argument("--blockers", nargs="+", help="")
    parser.add_argument("--notes", default="", help="")
    parser.add_argument("--interactive", action="store_true", help="")
    args = parser.parse_args()

    generator = DailyStandupGenerator(Path(args.output_dir))

    if args.interactive:
        print(" ")
        print("="*40)

        completed = []
        print("\n ():")
        while True:
            item = input("  > ")
            if not item.strip():
                break
            completed.append(item)

        today = []
        print("\n ():")
        while True:
            item = input("  > ")
            if not item.strip():
                break
            today.append(item)

        blockers = []
        print("\n ():")
        while True:
            item = input("  > ")
            if not item.strip():
                break
            blockers.append(item)

        notes = input("\n: ") or ""

        metrics = {
            "sched_latency_ms": 350,
            "recovery_time_s": 3.2,
            "gpu_util": 87,
            "sla_compliance": 99.95
        }

        phase_progress = {
            "phase1": 50,
            "phase2": 0,
            "phase3": 0
        }

    else:
        completed = args.completed or [""]
        today = args.today or [""]
        blockers = args.blockers or [""]
        notes = args.notes

        # 
        metrics = {
            "sched_latency_ms": 350,
            "recovery_time_s": 3.2,
            "gpu_util": 87,
            "sla_compliance": 99.95
        }

        phase_progress = {
            "phase1": 50,
            "phase2": 0,
            "phase3": 0
        }

    # 
    report = generator.generate_report(
        completed=completed,
        today=today,
        blockers=blockers,
        metrics=metrics,
        phase_progress=phase_progress,
        notes=notes
    )

    print("\n" + "="*60)
    print(" ")
    print("="*60)
    print(report)

    # 
    filepath = generator.save_report(report)
    print(f"\n : cat {filepath}")

if __name__ == "__main__":
    main()
