"""
CI Comment Formatter - Format proof results for PR comments
"""

from typing import List, Dict, Any
import structlog

from hermes.ci.types import CIProofReport, ProofResult, ProofResultStatus

logger = structlog.get_logger()


class CICommentFormatter:
    """
    Formats proof results into Markdown for GitHub PR comments.
    
    Generates:
    - Summary statistics
    - Detailed table of results
    - Generated test cases
    - Recommendations
    """
    
    def __init__(self):
        self.markers = {
            ProofResultStatus.PROVEN: "[PROVEN]",
            ProofResultStatus.DISPROVEN: "[DISPROVEN]",
            ProofResultStatus.TIMEOUT: "[TIMEOUT]",
            ProofResultStatus.UNKNOWN: "[UNKNOWN]",
            ProofResultStatus.CACHED: "[CACHED]"
        }
    
    def format_report(self, report: CIProofReport) -> str:
        """
        Format a CI proof report into Markdown.
        
        Args:
            report: CIProofReport to format
        
        Returns:
            Markdown string for PR comment
        """
        sections = []
        
        sections.append(self._format_header())
        sections.append(self._format_summary(report))
        sections.append(self._format_results_table(report.results))
        
        if report.total_disproven > 0:
            sections.append(self._format_generated_tests(report))
        
        sections.append(self._format_recommendations(report))
        sections.append(self._format_footer(report))
        
        return "\n\n".join(sections)
    
    def _format_header(self) -> str:
        """Format the comment header"""
        return """## AutoTestGen 

 PR """
    
    def _format_summary(self, report: CIProofReport) -> str:
        """Format the summary section"""
        total = report.total_proven + report.total_disproven + report.total_timeout + report.total_unknown
        
        summary = f"""### 

|  |  |
|------|------|
| **** | {report.total_proven} |
| **** | {report.total_disproven} |
| **** | {report.total_timeout} |
| **** | {report.total_unknown} |
| **** | {report.total_cached} |
| **** | {report.total_duration:.2f}s |
| **** | {report.cache_hit_rate:.1%} |"""
        
        return summary
    
    def _format_results_table(self, results: List[ProofResult]) -> str:
        """Format the results table"""
        if not results:
            return """### 

"""
        
        rows = []
        for result in results:
            marker = self.markers.get(result.status, "[UNKNOWN]")
            status_text = self._get_status_text(result.status)
            
            if result.cached:
                status_text += " ()"
            
            duration = f"{result.duration:.2f}s"
            
            rows.append(f"| `{result.function_name}` | {marker} {status_text} | {duration} | - |")
        
        return f"""### 

|  |  | (s) |  |
|------|---------|--------|------|
{chr(10).join(rows)}"""
    
    def _get_status_text(self, status: ProofResultStatus) -> str:
        """Get human-readable status text"""
        status_map = {
            ProofResultStatus.PROVEN: "",
            ProofResultStatus.DISPROVEN: "",
            ProofResultStatus.TIMEOUT: "",
            ProofResultStatus.UNKNOWN: "",
            ProofResultStatus.CACHED: ""
        }
        return status_map.get(status, str(status.value))
    
    def _format_generated_tests(self, report: CIProofReport) -> str:
        """Format generated tests section"""
        all_tests = []
        for result in report.results:
            if result.generated_tests:
                all_tests.extend(result.generated_tests)
        
        if not all_tests:
            return ""
        
        test_list = "\n".join([f"- `{t}`" for t in all_tests])
        
        return f"""### 



{test_list}"""
    
    def _format_recommendations(self, report: CIProofReport) -> str:
        """Format recommendations section"""
        recommendations = []
        
        if report.total_disproven > 0:
            recommendations.append("- ")
        
        if report.total_timeout > 0:
            recommendations.append("- ")
        
        if report.cache_hit_rate < 0.5:
            recommendations.append("- ")
        
        if not recommendations:
            recommendations.append("- ")
        
        return f"""### 

{'\n'.join(recommendations)}"""
    
    def _format_footer(self, report: CIProofReport) -> str:
        """Format the footer"""
        return """---

*Generated by AutoTestGen CI Pipeline*

[](https://github.com/AutoTestGen/autotestgen) | [](https://docs.autotestgen.io)"""
    
    def format_detailed_report(self, report: CIProofReport) -> str:
        """
        Format a detailed report with expanded information.
        
        Args:
            report: CIProofReport to format
        
        Returns:
            Detailed Markdown string
        """
        sections = []
        
        sections.append(self._format_header())
        sections.append(self._format_summary(report))
        
        if report.results:
            sections.append("\n### ")
            
            for i, result in enumerate(report.results, 1):
                marker = self.markers.get(result.status, "[UNKNOWN]")
                status_text = self._get_status_text(result.status)
                
                section = f"""#### {i}. `{result.function_name}`
                
- ****: {marker} {status_text}
- ****: `{result.filename}`
- ****: {result.duration:.2f}s
- ****: {'' if result.cached else ''}"""
                
                if result.generated_tests:
                    tests = ", ".join(result.generated_tests)
                    section += f"\n- ****: {tests}"
                
                if result.error_message:
                    section += f"\n- ****: {result.error_message}"
                
                sections.append(section)
        
        sections.append(self._format_recommendations(report))
        sections.append(self._format_footer(report))
        
        return "\n\n".join(sections)
    
    def format_error(self, error_message: str) -> str:
        """
        Format an error message for PR comment.
        
        Args:
            error_message: Error message to display
        
        Returns:
            Markdown string with error
        """
        return f"""## AutoTestGen 

### 



```
{error_message}
```

"""
